# Generated by Django 3.0.6 on 2020-05-22 14:51

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ventas_categorias',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('estado', django_fsm.FSMIntegerField(choices=[(0, 'creado'), (1, 'pagado'), (2, 'facturado'), (3, 'finalizado'), (-1, 'cancelado'), (-2, 'anulado')], default=0, protected=True)),
                ('factura_nombre', models.CharField(max_length=100, null=True)),
                ('factura_nit', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ventas_ventas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=50)),
                ('stock_actual', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='ventas.Categoria')),
            ],
            options={
                'db_table': 'ventas_productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Producto', to='ventas.Producto')),
                ('fk_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Venta', to='ventas.Venta')),
            ],
            options={
                'db_table': 'ventas_detalles_ventas',
            },
        ),
    ]
