# Generated by Django 3.0.6 on 2020-05-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='fk_producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='fk_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fk_categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
