# Generated by Django 3.0.6 on 2020-05-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_categoria_detalleventa_producto_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='motivo_anulacion',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
